include:
  - compose.kafka.yaml

services:

  dag-scheduler-service:
    restart: unless-stopped
    build:
      context: .
      dockerfile: dag-scheduler-service.Dockerfile
    ports:
      - 3002:3002
      - 50053:50053
    environment:
      ENVIRONMENT: production
      USE_NOOP_DB: false
      USE_NOOP_MQ: false
      USE_NOOP_STORE: false
      USE_NOOP_RAW_VIDEO_SERVICE: false

      API_PORT: 3002
      GRPC_PORT: 50053

      STORE_BUCKET: not-youtube
      MINIO_URI: dag-scheduler-service-minio:9000
      MINIO_SERVER_ACCESS_KEY: minio-access-key
      MINIO_SERVER_SECRET_KEY: minio-secret-key

      KAFKA_BROKERS: kafka:9092
      MQ_TOPIC_RAW_VIDEO: raw-video
      MQ_TOPIC_DAG: dag
    depends_on:
      - kafka
      - dag-scheduler-service-minio
    networks:
      - default

  dag-scheduler-service-postgres:
    restart: unless-stopped
    image: postgres:17.2
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: not_youtube
    ports:
      - 5432:5432
    networks:
      - default

  dag-scheduler-service-minio:
    restart: unless-stopped
    image: bitnami/minio:2024.9.22    
    environment:
      - MINIO_ROOT_USER=minio-access-key
      - MINIO_ROOT_PASSWORD=minio-secret-key
    ports:
      - 9000:9000
    networks:
      - default

networks:
  default: {}

