

services:

  mongo:
    restart: on-failure:3
    image: mongo:8.0.0
    ports:
      - 27017:27017
    networks:
      - default

  minio:
    restart: on-failure:3
    image: bitnami/minio:2024.9.22    
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=minio-access-key
      - MINIO_ROOT_PASSWORD=minio-secret-key
    networks:
      - default

networks:
  default: {}

