include:
  - compose.kafka.yaml

services:

  preprocessor-service-postgres:
    restart: unless-stopped
    image: postgres:17.2
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: not_youtube
    ports:
      - 5432:5432
    networks:
      - default

  preprocessor-service:
    restart: unless-stopped
    build:
      context: .
      dockerfile: preprocessor-service.Dockerfile
    ports:
      - 3001:3001
    environment:
      ENVIRONMENT: production
      USE_NOOP_DB: true
      USE_NOOP_MQ: false
      USE_NOOP_STORE: true

      KAFKA_BROKERS: kafka:9092
      MQ_TOPIC_RAW_VIDEO: raw-video
      MQ_TOPIC_DAG: dag
    depends_on:
      - kafka
    networks:
      - default

networks:
  default: {}

