// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: dags.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDAG = `-- name: CreateDAG :one
INSERT INTO dags (id)
VALUES ($1)
RETURNING id, created_at
`

func (q *Queries) CreateDAG(ctx context.Context, id pgtype.UUID) (Dag, error) {
	row := q.db.QueryRow(ctx, createDAG, id)
	var i Dag
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const getDAG = `-- name: GetDAG :one
SELECT id, created_at FROM dags WHERE id = $1
`

func (q *Queries) GetDAG(ctx context.Context, id pgtype.UUID) (Dag, error) {
	row := q.db.QueryRow(ctx, getDAG, id)
	var i Dag
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
